services:
  db:
    container_name: db
    image: scylladb/scylla
    command: --smp 1 --memory 1G --overprovisioned 1
    ports:
      - "9180:9180"
      - "9160:9160"
      - "9042:9042"
      - "19042:19042"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 10s
      timeout: 5s
      retries: 10
